using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace EsirDriver.Modeli.esir
{
    public class EsirInvoiceFromDbModel
    {
        public bool autoGenerated { get; set; }
        public List<PaymentModel> fiscalizedPayment { get; set; } = new List<PaymentModel>();

        public InvoiceRequest invoiceRequest { get; set; }

        public InvoiceResponseModel invoiceResponse { get; set; }

        public bool issueCopy { get; set; }
        public bool print {  get; set; }

        public string receiptImageBase64 { get; set; }

        public ReceptImageFormat receiptImageFormat { get; set; }
        public ReceiptLayoutType receiptLayout { get; set; }
        public bool renderReceiptImage { get; set; }
        public bool skipEftPos { get; set; }
        public bool skipEftPosPrint { get; set; }

    }
}
